# Generated by Django 4.2.20 on 2026-06-11 22:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_customers", models.PositiveIntegerField(default=0)),
                ("total_products_sold", models.PositiveIntegerField(default=0)),
                ("total_page_views", models.PositiveIntegerField(default=0)),
                ("total_visitors", models.PositiveIntegerField(default=0)),
                ("total_searches", models.PositiveIntegerField(default=0)),
                ("conversion_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("top_products", models.JSONField(blank=True, default=list)),
                ("traffic_sources", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("product_view", "Product View"),
                            ("add_to_cart", "Add to Cart"),
                            ("purchase", "Purchase"),
                            ("search", "Search"),
                            ("signup", "Sign Up"),
                            ("newsletter_subscribe", "Newsletter Subscribe"),
                            ("click", "Click"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_type", models.CharField(blank=True, default="", max_length=100)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("session_id", models.CharField(blank=True, default="", max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("referrer", models.URLField(blank=True, default="")),
                ("url", models.URLField(blank=True, default="")),
                ("visitor_id", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
