# Generated by Django 4.2.20 on 2026-06-11 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("analytics", "0002_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_events",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_stats",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_stats",
                to="stores.store",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organization", "store", "event_type"],
                name="analytics_e_organiz_7adca3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organization", "created_at"], name="analytics_e_organiz_b41917_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["visitor_id"], name="analytics_e_visitor_0db219_idx"),
        ),
        migrations.AddIndex(
            model_name="dailystats",
            index=models.Index(fields=["store", "date"], name="analytics_d_store_i_e062c6_idx"),
        ),
        migrations.AddIndex(
            model_name="dailystats",
            index=models.Index(
                fields=["organization", "date"], name="analytics_d_organiz_9d6559_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailystats",
            unique_together={("store", "date")},
        ),
    ]
