maxmemory 768mb
maxmemory-policy allkeys-lru
requirepass VQ2vwcLbWEN_-dYMN2j16ZZOLC8pBkLCdG5t36afA_0
save 900 1
save 300 10
save 60 10000
appendonly yes
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
hz 10
