# Generated by Django 4.2.20 on 2026-06-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='theme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing', to='themes.theme'),
        ),
        migrations.AlterUniqueTogether(
            name='marketplacereview',
            unique_together={('listing', 'user')},
        ),
    ]
