# Generated by Django 4.2.20 on 2026-06-16 20:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0003_mediaasset_media_media_organiz_b15803_idx_and_more"),
        ("organizations", "0002_organizationmembership_organizatio_user_id_97f34b_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stores", "0004_add_og_image_twitter_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("bio", models.TextField(blank=True, default="")),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("translations", models.JSONField(blank=True, default=dict)),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_author_avatars",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_authors",
                        to="organizations.organization",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_authors",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_author_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                ("seo_description", models.TextField(blank=True, default="")),
                ("translations", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_category_images",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_category_og_images",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_categories",
                        to="organizations.organization",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_categories",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=500)),
                ("excerpt", models.TextField(blank=True, default="")),
                ("content", models.TextField(blank=True, default="")),
                ("featured_image_alt", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("scheduled", "Scheduled"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                ("seo_description", models.TextField(blank=True, default="")),
                (
                    "twitter_card",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary_large_image",
                        max_length=20,
                    ),
                ),
                ("canonical_url", models.URLField(blank=True, default="", max_length=500)),
                ("focus_keyword", models.CharField(blank=True, default="", max_length=255)),
                ("translations", models.JSONField(blank=True, default=dict)),
                (
                    "reading_time",
                    models.IntegerField(default=0, help_text="Estimated reading time in minutes"),
                ),
                ("allow_comments", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("view_count", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.blogauthor",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("translations", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_tags",
                        to="organizations.organization",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_tags",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("organization", "store", "slug")},
            },
        ),
        migrations.CreateModel(
            name="BlogPostTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_tags",
                        to="blog.blogpost",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_posts",
                        to="blog.blogtag",
                    ),
                ),
            ],
            options={
                "unique_together": {("post", "tag")},
            },
        ),
        migrations.CreateModel(
            name="BlogPostCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_posts",
                        to="blog.blogcategory",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_categories",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("post", "category")},
            },
        ),
        migrations.AddField(
            model_name="blogpost",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                through="blog.BlogPostCategory",
                to="blog.blogcategory",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_post_images",
                to="media.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_post_og_images",
                to="media.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", through="blog.BlogPostTag", to="blog.blogtag"
            ),
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_name", models.CharField(blank=True, default="", max_length=255)),
                ("author_email", models.EmailField(blank=True, default="", max_length=254)),
                ("author_website", models.URLField(blank=True, default="", max_length=500)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("spam", "Spam"),
                            ("trash", "Trash"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_guest", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_comments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.blogcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpost",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_comments",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_subscribers",
                        to="organizations.organization",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_subscribers",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-subscribed_at"],
                "unique_together": {("organization", "store", "email")},
            },
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["organization", "store", "status"], name="blog_blogpo_organiz_281328_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["organization", "store", "published_at"],
                name="blog_blogpo_organiz_d347cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["organization", "store", "is_featured"],
                name="blog_blogpo_organiz_559b46_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blogpost",
            unique_together={("organization", "store", "slug")},
        ),
        migrations.AddIndex(
            model_name="blogcomment",
            index=models.Index(
                fields=["organization", "store", "post", "status"],
                name="blog_blogco_organiz_8300ff_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blogcategory",
            unique_together={("organization", "store", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="blogauthor",
            unique_together={("organization", "store", "slug")},
        ),
    ]
