# Generated by Django 4.2.20 on 2026-06-17 00:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organizationmembership_organizatio_user_id_97f34b_idx"),
        ("stores", "0004_add_og_image_twitter_card"),
        ("blog", "0001_initial_blog_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("posts_per_page", models.PositiveIntegerField(default=10)),
                (
                    "default_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("allow_comments", models.BooleanField(default=True)),
                ("comment_moderation", models.BooleanField(default=True)),
                ("show_author_bio", models.BooleanField(default=True)),
                ("rss_enabled", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_settings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_settings",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "blog settings",
            },
        ),
    ]
