# Generated by Django 4.2.20 on 2026-06-11 22:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Theme configuration: colors, typography, spacing, borderRadius, animations, darkMode",
                    ),
                ),
                (
                    "sections_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Available section definitions for this theme",
                    ),
                ),
                (
                    "assets",
                    models.JSONField(blank=True, default=dict, help_text="CSS variables, JS hooks"),
                ),
                (
                    "is_system",
                    models.BooleanField(default=False, help_text="System themes cannot be deleted"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means system theme",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent_theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_themes",
                        to="themes.theme",
                    ),
                ),
                (
                    "preview_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theme_previews",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ThemePreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Color/font overrides for this preset"
                    ),
                ),
                (
                    "preview_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theme_preset_previews",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presets",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("theme", "name")},
            },
        ),
    ]
