# Generated by Django 4.2.20 on 2026-06-11 22:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="New Conversation", max_length=255)),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("chat", "General Chat"),
                            ("product_gen", "Product Generation"),
                            ("content_gen", "Content Generation"),
                            ("analytics", "Analytics Assistant"),
                            ("support", "Customer Support"),
                        ],
                        default="chat",
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("total_tokens_used", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIGenerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("product_description", "Product Description"),
                            ("product_title", "Product Title"),
                            ("seo_title", "SEO Title"),
                            ("seo_description", "SEO Description"),
                            ("marketing_copy", "Marketing Copy"),
                            ("blog_post", "Blog Post"),
                            ("email", "Email"),
                            ("store_description", "Store Description"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prompt", models.TextField()),
                ("result", models.TextField(blank=True, default="")),
                ("provider", models.CharField(blank=True, default="", max_length=50)),
                ("model_name", models.CharField(blank=True, default="", max_length=100)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("is_success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("assistant", "Assistant"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("gemini", "Google Gemini"),
                            ("ollama", "Ollama (Local)"),
                            ("groq", "Groq"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(default="gpt-4o-mini", max_length=100)),
                ("api_key", models.CharField(blank=True, default="", max_length=500)),
                ("api_base_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("max_tokens", models.IntegerField(default=4096)),
                ("temperature", models.FloatField(default=0.7)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
