# Generated by Django 4.2.20 on 2026-06-11 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation'),
        ),
        migrations.AddField(
            model_name='aigenerationlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_logs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='aigenerationlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='ai.aiprovider'),
        ),
    ]
