# Generated by Django 5.1.15 on 2026-06-18 22:56

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auditlog',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
