# Generated by Django 4.2.20 on 2026-06-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token_hash",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token_hash",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
