# Generated by Django 4.2.20 on 2026-06-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_migrate_existing_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
