# Generated by Django 4.2.20 on 2026-06-13 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('restaurant', 'Restaurant & Cafe'), ('pharmacy', 'Pharmacy & Medical'), ('furniture', 'Furniture & Home Decor'), ('general', 'General')], default='general', max_length=50)),
                ('author', models.CharField(default='Tujjar', max_length=255)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=512)),
                ('preview_images', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('presets', models.JSONField(blank=True, default=list)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('navigation', models.JSONField(blank=True, default=dict)),
                ('footer', models.JSONField(blank=True, default=dict)),
                ('seo_defaults', models.JSONField(blank=True, default=dict)),
                ('demo_content', models.JSONField(blank=True, default=dict)),
                ('store_settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='templates_t_categor_d27f13_idx'), models.Index(fields=['is_system'], name='templates_t_is_syst_a881d0_idx')],
            },
        ),
    ]
