# Generated by Django 4.2.20 on 2026-06-18 00:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stores", "0004_add_og_image_twitter_card"),
        ("templates", "0002_add_templateversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreBackup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pages", models.JSONField(blank=True, default=list)),
                ("navigation", models.JSONField(blank=True, default=dict)),
                ("footer", models.JSONField(blank=True, default=dict)),
                ("seo_defaults", models.JSONField(blank=True, default=dict)),
                ("theme_config", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_backups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_backups",
                        to="stores.store",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_backups",
                        to="templates.template",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
