# Generated by Django 4.2.20 on 2026-06-11 22:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("file_url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True, default="")),
                ("cdn_url", models.URLField(blank=True, default="")),
                ("storage_backend", models.CharField(default="local", max_length=20)),
                ("storage_path", models.CharField(blank=True, default="", max_length=500)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("alt_text", models.CharField(blank=True, default="", max_length=255)),
                ("title_attr", models.CharField(blank=True, default="", max_length=255)),
                ("used_in_products", models.PositiveIntegerField(default=0)),
                ("used_in_pages", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(blank=True, default="", max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_folders",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="media.mediafolder",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
