# Generated by Django 4.2.20 on 2026-06-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('organizations', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafolder',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to='stores.store'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='media.mediafolder'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='mediafolder',
            unique_together={('store', 'name', 'parent')},
        ),
    ]
