# Generated by Django 4.2.20 on 2026-07-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
