# Generated by Django 4.2.20 on 2026-06-11 22:09

from django.db import migrations, models
import django.db.models.deletion
import secrets
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('themes', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_favicons', to='media.mediaasset')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_logos', to='media.mediaasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='organizations.organization')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='themes.theme')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StoreDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(default=secrets.token_urlsafe, max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='stores.store')),
            ],
            options={
                'ordering': ['-is_primary', 'domain'],
            },
        ),
    ]
