# Generated by Django 4.2.20 on 2026-06-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='footer_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='store',
            name='navigation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='store',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='templates.template'),
        ),
    ]
