# Generated by Django 4.2.20 on 2026-06-15 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0003_mediaasset_media_media_organiz_b15803_idx_and_more"),
        ("stores", "0003_store_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_og_images",
                to="media.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="twitter_card",
            field=models.CharField(
                choices=[("summary", "Summary"), ("summary_large_image", "Summary Large Image")],
                default="summary_large_image",
                max_length=20,
            ),
        ),
    ]
