# Generated by Django 4.2.20 on 2026-06-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization', 'is_active'], name='products_ca_organiz_078a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization', 'store'], name='products_ca_organiz_38b0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['organization', 'is_active'], name='products_co_organiz_723887_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['organization', 'store'], name='products_co_organiz_b37fec_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'status'], name='products_pr_organiz_c7c18b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'store'], name='products_pr_organiz_bc2dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'status'], name='products_pr_store_i_ce0433_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'track_inventory', 'inventory_quantity'], name='products_pr_status_7b970e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_pr_product_cea9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
    ]
