# Generated by Django 4.2.20 on 2026-06-18 17:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0003_mediaasset_media_media_organiz_b15803_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0003_category_translations_collection_translations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("position", models.PositiveSmallIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("product", "name")},
            },
        ),
        migrations.AddField(
            model_name="category",
            name="seo_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="collection",
            name="seo_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="collection",
            name="seo_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="productimage",
            name="media_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_images",
                to="media.mediaasset",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adjustment",
                    models.IntegerField(help_text="Positive for increase, negative for decrease"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("adjustment", "Manual Adjustment"),
                            ("restock", "Restock"),
                            ("correction", "Correction"),
                            ("return", "Return"),
                        ],
                        default="adjustment",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Order ID or reference note",
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_movements",
                        to="products.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_movements",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductOptionValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=100)),
                (
                    "swatch",
                    models.CharField(
                        blank=True, default="", help_text="Hex color, e.g. #FF0000", max_length=7
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="products.productoption",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "value"],
                "unique_together": {("option", "value")},
            },
        ),
    ]
