name: Sync to Production

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to private repo
        uses: cpina/github-action-push-to-another-repository@v1
        with:
          source-directory: '.'
          destination-github-username: 'dev-taherm'
          destination-repository-name: 'Tujjar-production'
          user-email: 'taher@dev.com'
          target-branch: 'main'
          commit-message: 'sync from public repo'
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
